--CREATE DATABASE PROGRAMA;

--CREATE SEQUENCE SEQ_CLI_CODIGO;
/*
CREATE TABLE CLIENTE (
  CLI_CODIGO         INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_CLI_CODIGO') ,
  CLI_NOME           VARCHAR(100) NOT NULL,
  CLI_CPF            VARCHAR(11),
  CLI_RG             VARCHAR(20),
  CLI_CNPJ           VARCHAR(14),
  CLI_TIPO_PESSOA    INTEGER NOT NULL,
  CLI_ENDERECO       VARCHAR(150),
  CLI_NUMERO         VARCHAR(10),
  CLI_CEP            VARCHAR(8),
  CLI_CIDADE         VARCHAR(30),
  CLI_UF             VARCHAR(2),
  CLI_LIMITE_CREDITO NUMERIC(10,2),
  CLI
  CLI_DTHR_CADASTRO  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
*/
--COMMENT ON COLUMN CLIENTE.CLI_TIPO_PESSOA IS '1-PESSOA FISICA, 2-PESSOA JURIDICA';

--ALTER TABLE CLIENTE ADD CLI_DATA_NASCIMENTO DATE;





